server:
  port: 9091

spring:
  application:
    name: gateway-oidc

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: dm91bWVnYS5yZWFsbS5uby5yb2xlLmZvci5rZXljbG9hazI2LjMuMQo
            client-secret: uBkBnoJoJYJknWQ53Jr2yayV4CzqfiYD
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/voomega-oidc/realms/VOOMEGA-REALM
            user-name-attribute: preferred_username

  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: resource-server
          uri: http://localhost:8280
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
